group: travis_latest
language: cpp

git:
  depth: 4

env:
  global:
   - secure: "TdT9Gj2QhbsjwGvEP1fosSxNdYFDfemAWzkwE2tX/iWy5gFFqmKsyr6GIvbqYLvtWwCiL/8ahZBfUL1as1ZbJci0dgMNCqj4quA6G3OvibA+VB9NXRRM0Il/p/3TDTm+nzO2Z1TkECtuzJkco2CHaDZQIdg/ul3zSyAGL+OSYSg="

matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc

addons:
  apt:
    packages:
      - qt5-default
      - qtbase5-dev
      - libqt5opengl5-dev
      - libboost-dev
      - libcgal-dev
      - bison
      - flex
      - libreadline-dev
  coverity_scan:
    project:
      name: "GilesBathgate/RapCAD"
      description: "Build submitted via Travis CI"
    notification_email: gilesbathgate@gmail.com
    build_command_prepend: "qmake CONFIG+=official"
    build_command:   "make -j2"
    branch_pattern: coverity_scan

install:
- export CGAL_DIR=/usr/include/CGAL;
- export BOOST_ROOT=/usr/include/boost;
- sudo patch -l $BOOST_ROOT/random/linear_congruential.hpp < patch/Fix-Wtautological-overlap-compare-clang-warning.patch;
- sudo patch -l $CGAL_DIR/Nef_S2/SM_overlayer.h < patch/Fix-use-of-uninitialized-variable-in-SM_overlayer.h.patch;
- sudo patch -l $CGAL_DIR/IO/File_scanner_OFF.h < patch/Fix-use-of-uninitialized-variable-in-File_scanner_OFF.h.patch;
- sudo patch -l $CGAL_DIR/IO/File_writer_OFF.h < patch/Fix-uninitialized-member-in-File_writer_OFF.h.patch;
- sudo patch -l $CGAL_DIR/IO/File_writer_VRML_2.h < patch/Fix-uninitialized-member-in-File_writer_VRML_2.h.patch;
- sudo patch -l $CGAL_DIR/internal/Triangulation_ds_iterators_3.h < patch/Fix-uninitialized-member-in-Triangulation_ds_iterators_3.h.patch;
- sudo patch -l $CGAL_DIR/Triangulation_2/internal/Triangulation_line_face_circulator_2.h < patch/Fix-uninitialized-member-in-Triangulation_line_face_circulator_2.h.patch;
- sudo patch -l $CGAL_DIR/Triangulation_3.h < patch/Fix-uninitialized-member-in-Triangulation_3.h.patch;
- sudo patch -l $CGAL_DIR/Tools/chained_map.h < patch/Fix-uninitialized-member-in-chained_map.h.patch;
- sudo patch -l $CGAL_DIR/Nef_3/ID_support_handler.h < patch/Performance-in-ID_support_handler.h.patch;
- sudo patch -l $CGAL_DIR/Nef_3/K3_tree.h < patch/Fix-uninitialized-member-in-K3_tree.h.patch;
- sudo patch -l $CGAL_DIR/Mpzf.h < patch/Fix-uninitialized-member-in-Mpzf.h.patch;
- sudo patch -l $CGAL_DIR/GMP/Gmpz_type.h < patch/Fix-uninitialized-member-in-Gmpz_type.h.patch;
- sudo patch -l $CGAL_DIR/GMP/Gmpfr_type.h < patch/Fix-uninitialized-member-in-Gmpfr_type.h.patch;
- sudo patch -l $CGAL_DIR/Multiset.h < patch/Fix-uninitialized-members-in-Multiset.h.patch;
- sudo patch -l $CGAL_DIR/Convex_decomposition_3/Single_wall_creator.h < patch/Fix-uninitialized-member-in-Single_wall_creator.h.patch;
- sudo patch -l $CGAL_DIR/Convex_decomposition_3/Edge_sorter.h < patch/Fix-uninitialized-member-in-Edge_sorter.h.patch;
- sudo patch -l $CGAL_DIR/Convex_decomposition_3/Ray_hit_generator2.h < patch/Fix-uninitialized-members-in-Ray_hit_generator2.h.patch;
- sudo patch -l $CGAL_DIR/Nef_3/SNC_io_parser.h < patch/Fix-uninitialized-member-in-SNC_io_parser.h.patch;
- sudo patch -l $CGAL_DIR/Nef_3/Volume.h < patch/Fix-uninitialized-member-in-Volume.h.patch;
- sudo patch -l $CGAL_DIR/Polyhedron_incremental_builder_3.h < patch/Fix-uninitialized-member-in-Polyhedron_incremental_builder.h.patch;
- sudo patch -l $CGAL_DIR/Triangulation_vertex_base_with_info_2.h < patch/Fix-uninitialized-member-in-Triangulation_vertex_base_with_info_2.h.patch;
- sudo patch -l $CGAL_DIR/utility.h < patch/Fix-uninitialized-members-in-utility.h.patch;
- sudo patch -l $CGAL_DIR/boost/graph/iterator.h < patch/Fix-uninitialized-member-in-iterator.h.patch;
- sudo patch -l $CGAL_DIR/Straight_skeleton_2/Straight_skeleton_builder_events_2.h < patch/Fix-uninitialized-member-in-Straight_skeleton_builder_events_2.h.patch;
- sudo patch -l $CGAL_DIR/Filtered_predicate.h < patch/Fix-uninitialized-member-in-Filtered_predicate.h.patch;
- sudo patch -l $CGAL_DIR/Intersections_2/Segment_2_Segment_2.h < patch/Fix-uninitialized-member-in-Segment_2_Segment_2.h.patch;
- sudo patch -l $CGAL_DIR/Mpzf.h < patch/Fix-dead-code-warning-in-Mpzf.h.patch;
- sudo patch -l $CGAL_DIR/Nef_3/Vertex.h < patch/Fix-dereference-after-null-check-in-Nef_3-Vertex.h.patch;
- sudo patch -l $CGAL_DIR/Nef_3/SNC_io_parser.h < patch/Fix-passing-big-parameters-by-value-in-SNC_io_parser.patch;
- sudo patch -l $CGAL_DIR/Intersections_2/Line_2_Line_2.h < patch/Fix-uninitialized-member-in-Line_2_Line_2.h.patch;

script:
  - qmake -v
