group: travis_latest
language: cpp

env:
  global:
   - secure: "TdT9Gj2QhbsjwGvEP1fosSxNdYFDfemAWzkwE2tX/iWy5gFFqmKsyr6GIvbqYLvtWwCiL/8ahZBfUL1as1ZbJci0dgMNCqj4quA6G3OvibA+VB9NXRRM0Il/p/3TDTm+nzO2Z1TkECtuzJkco2CHaDZQIdg/ul3zSyAGL+OSYSg="

matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc

addons:
  apt:
    packages:
      - qt5-default
      - qtbase5-dev
      - libqt5opengl5-dev
      - libboost-dev
      - libcgal-dev
      - bison
      - flex
      - libreadline-dev
  coverity_scan:
    project:
      name: "GilesBathgate/RapCAD"
      description: "Build submitted via Travis CI"
    notification_email: gilesbathgate@gmail.com
    build_command_prepend: "qmake CONFIG+=official"
    build_command:   "make -j4"
    branch_pattern: coverity_scan

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      brew link --force qt5;
    fi

script:
  - qmake -v

notifications:
  irc:
    channels:
      - "irc.freenode.org#rapcad"
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
