language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default qtbase5-dev libqt5opengl5-dev libboost-dev libcgal-dev bison flex libreadline-dev
script:
  - qmake -qt5
  - make -j4
  - pushd test
  - ../rapcad -t
notifications:
  irc:
    channels:
      - "irc.freenode.org#rapcad"
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
