language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt50
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default qtbase5-dev libqt5opengl5-dev libboost-dev libcgal-dev bison flex libreadline-dev
  - export QMAKE=/opt/qt5/bin/qmake
script: qmake && make
