group: travis_latest
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
      - qt5-default
      - qtbase5-dev
      - libqt5opengl5-dev
      - libboost-dev
      - libcgal-dev
      - bison
      - flex
      - libreadline-dev

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
      brew install qt5;
      brew link --force qt5;
    fi

before_script:
  - if [ $TRAVIS_OS_NAME != osx ]; then
       export DISPLAY=:99.0;
       sh -e /etc/init.d/xvfb start;
    fi

script:
  - qmake -v
  - qmake CONFIG+=coverage
  - make -j4
  - if [ $TRAVIS_OS_NAME = osx ]; then
      path="../rapcad.app/Contents/MacOS";
    else
      path="..";
    fi;
    pushd test &&
    $path/rapcad -t &&
    popd

after_success:
  - if [ $TRAVIS_OS_NAME != osx ]; then
      bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov) -a '-r';
    fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#rapcad"
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
