sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
      - qt5-default
      - qtbase5-dev
      - libqt5opengl5-dev
      - libboost-dev
      - libcgal-dev
      - bison
      - flex
      - libreadline-dev

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      brew update;
      brew install qt5;
      brew link --force qt5;
    fi

script:
  - qmake -v
  - qmake
  - make -j4
  - pushd test
  - ../rapcad -t

notifications:
  irc:
    channels:
      - "irc.freenode.org#rapcad"
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
