group: travis_latest
language: cpp
jobs:
  include:
  - os: linux
    dist: focal
    compiler: gcc
    env: CONFIG=coverage
  - os: osx
    osx_image: xcode12.2
    compiler: clang
    env: CONFIG=coverage
  - if: branch = master OR tag IS present
    os: osx
    osx_image: xcode12.2
    compiler: clang
    env: CONFIG=official

addons:
  apt:
    packages:
    - qt5-default
    - qtbase5-dev
    - libqt5opengl5-dev
    - libboost-dev
    - libcgal-dev
    - bison
    - flex
    - libreadline-dev

install:
- if [ $TRAVIS_OS_NAME = osx ]; then
    brew install bison;
    export PATH="/usr/local/opt/bison/bin:$PATH";
    brew link --force qt5;
  fi

script:
- export VERSION=$(cat VERSION)
- qmake -v
- qmake CONFIG+=$CONFIG
- make -j4
- if [ $CONFIG = coverage ]; then
    if [ $TRAVIS_OS_NAME = osx ]; then
      ./rapcad.app/Contents/MacOS/rapcad -t test;
    else
      xvfb-run --server-args="-screen 0 1024x768x24" ./rapcad -t test;
    fi
  fi
- if [ $CONFIG = official ]; then
    if [ $TRAVIS_OS_NAME = osx ]; then
      macdeployqt rapcad.app -dmg;
      mv rapcad.dmg rapcad_$VERSION.dmg;
    fi
  fi

after_success:
- if [ $TRAVIS_OS_NAME != osx ] && [ $CONFIG = coverage ]; then
    bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov) -a '-r';
  fi

deploy:
  provider: releases
  token:
    secure: mQDIQDIJLGeKGRtQmF/wc5YM9HiJ0tx8rDvX3NLuIwUSsI6RrmBwtXyqW0+CbT4tgPvZBbiyGhobK9hsOt2xtQKG4uhF+4kCmd9RZi3bLi4w1B3MwuCmtwLwZ0Z0d1hgtlWOnhVuOywxRbZFoem9/ckrFsVbu/LMucskyTzUl6s=
  file_glob: true
  file: rapcad_*.dmg
  edge: true
  draft: true
  on:
    branch: master
    condition: -e rapcad_$VERSION.dmg
    tags: true

notifications:
  irc:
    channels:
    - irc.freenode.org#rapcad
    skip_join: true
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Build details : %{build_url}'

